import { useEffect, useState } from "react";
import { toast } from "react-hot-toast";
import { createAddress, deleteAddress, getAddresses, setDefaultAddress, updateAddress } from "../../api/addressApi";
import StoreHeader from "../../components/StoreHeader";

const blank = { fullName: "", phoneNumber: "", addressLine1: "", addressLine2: "", city: "", state: "", country: "India", postalCode: "", isDefault: false };

export default function Addresses() {
  const [addresses, setAddresses] = useState([]); const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(null); const [saving, setSaving] = useState(false);
  const load = () => getAddresses().then(setAddresses).catch(() => toast.error("Unable to load addresses."));
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { if (editingId) await updateAddress(editingId, form); else await createAddress(form); toast.success(editingId ? "Address updated." : "Address saved."); setEditingId(null); setForm(blank); load(); } catch (error) { toast.error(error.response?.data?.message || "Unable to save address."); } finally { setSaving(false); } };
  const edit = (address) => { setEditingId(address.id); setForm({ ...blank, ...address }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const field = (key, optional = false) => <input key={key} required={!optional} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={key.replace(/([A-Z])/g, " $1")} className="rounded-xl border px-3 py-2.5" />;
  return <><StoreHeader /><main className="mx-auto min-h-screen max-w-6xl px-5 py-10 sm:px-8"><h1 className="text-4xl font-black">Your addresses</h1><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="space-y-4">{addresses.length ? addresses.map((address) => <article key={address.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-black">{address.fullName} {address.isDefault && <span className="ml-2 text-xs text-emerald-600">DEFAULT</span>}</h2><div className="flex gap-3"><button onClick={() => edit(address)} className="text-sm font-bold text-emerald-600">Edit</button><button onClick={async () => { try { await deleteAddress(address.id); toast.success("Address deleted."); load(); } catch { toast.error("Unable to delete address."); } }} className="text-sm font-bold text-red-600">Delete</button></div></div><p className="mt-2 text-sm text-slate-600">{address.addressLine1}{address.addressLine2 ? `, ${address.addressLine2}` : ""}<br />{address.city}, {address.state} {address.postalCode}<br />{address.country} · {address.phoneNumber}</p>{!address.isDefault && <button onClick={async () => { try { await setDefaultAddress(address.id); toast.success("Default address updated."); load(); } catch { toast.error("Unable to update default address."); } }} className="mt-4 text-sm font-bold text-emerald-600">Set as default</button>}</article>) : <p className="text-slate-500">No saved addresses yet.</p>}</section><form onSubmit={submit} className="h-fit rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{editingId ? "Edit address" : "Add an address"}</h2>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(blank); }} className="text-sm font-bold text-slate-500">Cancel</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{["fullName", "phoneNumber", "addressLine1", "city", "state", "country", "postalCode"].map((key) => field(key))}<div className="sm:col-span-2">{field("addressLine2", true)}</div></div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={form.isDefault} onChange={(event) => setForm({ ...form, isDefault: event.target.checked })} />Set as default</label><button disabled={saving} className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">{saving ? "Saving…" : editingId ? "Update address" : "Save address"}</button></form></div></main></>;
}
