/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { getBrands } from "../../api/brandApi";
import { getCategories } from "../../api/categoryApi";
import { filterProducts, getProducts } from "../../api/productApi";
import ProductCard from "../../components/ProductCard";
import StoreHeader from "../../components/StoreHeader";

function Products() {
  const [searchParams] = useSearchParams();
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [brands, setBrands] = useState([]); const [filters, setFilters] = useState({ keyword: searchParams.get("keyword") || "", category: searchParams.get("category") || "", brand: "", sortBy: "id", direction: "asc" }); const [page, setPage] = useState(0); const [totalPages, setTotalPages] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { setFilters((current) => ({ ...current, keyword: searchParams.get("keyword") || "", category: searchParams.get("category") || "" })); setPage(0); }, [searchParams]);
  useEffect(() => { Promise.all([getCategories(), getBrands()]).then(([categoryData, brandData]) => { setCategories(categoryData); setBrands(brandData); }).catch(() => {}); }, []);
  useEffect(() => { setLoading(true); setError(""); const params = { ...filters, page, size: 12 }; const hasFilters = filters.keyword || filters.category || filters.brand; (hasFilters ? filterProducts(params) : getProducts(params)).then((data) => { setProducts(data.content || []); setTotalPages(data.totalPages || 0); }).catch((err) => setError(err.response?.data?.message || "Unable to load products.")).finally(() => setLoading(false)); }, [filters, page]);
  const update = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(0); };
  return <><StoreHeader /><main className="mx-auto min-h-screen max-w-7xl px-5 py-10 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-bold text-emerald-600">NexCart catalogue</p><h1 className="mt-1 text-4xl font-black tracking-tight text-slate-950">Find something you’ll love</h1><p className="mt-3 text-slate-500">Explore products added and managed through the NexCart admin workspace.</p></div><section className="mt-8 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-4"><input value={filters.keyword} onChange={(event) => update("keyword", event.target.value)} placeholder="Search products" className="rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-emerald-500" /><select value={filters.category} onChange={(event) => update("category", event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><select value={filters.brand} onChange={(event) => update("brand", event.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5"><option value="">All brands</option>{brands.map((brand) => <option key={brand.id} value={brand.name}>{brand.name}</option>)}</select><select value={`${filters.sortBy}:${filters.direction}`} onChange={(event) => { const [sortBy, direction] = event.target.value.split(":"); setFilters((current) => ({ ...current, sortBy, direction })); setPage(0); }} className="rounded-xl border border-slate-300 px-3 py-2.5"><option value="id:asc">Newest added</option><option value="price:asc">Price: low to high</option><option value="price:desc">Price: high to low</option><option value="name:asc">Name: A–Z</option></select></section>{loading ? <p className="py-20 text-center text-slate-500">Loading products…</p> : error ? <p className="py-20 text-center text-red-600">{error}</p> : products.length ? <><section className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} />)}</section>{totalPages > 1 && <div className="mt-8 flex justify-center gap-3"><button disabled={!page} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm text-slate-600">Page {page + 1} of {totalPages}</span><button disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Next</button></div>}</> : <p className="py-20 text-center text-slate-500">No products match these filters yet.</p>}</main></>;
}
export default Products;
