spring.application.name=backend


# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/nexcart
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SERVER
# ===============================
server.port=8080
# ==========================
# JWT Configuration
# ==========================

jwt.secret=7Ew9Xk2mQ5rLp8YtN4cVz1As6DfGh3JkLm9PqRsTuVxYzAbCdEfGhIjKlMnOpQr
jwt.expiration=86400000
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
razorpay.key-id=rzp_test_TIpe3qQ7JofOrH
razorpay.key-secret= eVQhmjxTipxzRnHtq2S416pF


