package com.nexcart.recovery.controller;
import com.nexcart.entity.*; import com.nexcart.recovery.service.RecoveryService; import com.nexcart.repository.*; import com.razorpay.Utils; import lombok.RequiredArgsConstructor; import org.json.JSONObject; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.LocalDateTime; import java.util.Map;
@RestController @RequestMapping("/api/webhooks") @RequiredArgsConstructor public class RecoveryWebhookController {
 private final PaymentRepository payments; private final OrderRepository orders; private final RecoveryService recovery;
 @Value("${razorpay.webhook-secret:}") private String webhookSecret;
 @PostMapping(value="/razorpay",consumes=MediaType.APPLICATION_JSON_VALUE) public ResponseEntity<Map<String,String>> receive(@RequestBody String body,@RequestHeader(value="X-Razorpay-Signature",required=false) String signature) throws Exception {
  if(webhookSecret.isBlank()||signature==null||!Utils.verifyWebhookSignature(body,signature,webhookSecret))return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("message","Invalid webhook signature"));
  JSONObject root=new JSONObject(body), payload=root.optJSONObject("payload"); String event=root.optString("event");
  if("payment_link.paid".equals(event) && payload!=null){ JSONObject paymentLink=payload.optJSONObject("payment_link"); JSONObject payment=payload.optJSONObject("payment"); JSONObject linkEntity=paymentLink==null?null:paymentLink.optJSONObject("entity"); JSONObject paymentEntity=payment==null?null:payment.optJSONObject("entity"); if(linkEntity!=null){ recovery.handlePaymentLinkPaid(linkEntity.optString("id"),paymentEntity==null?null:paymentEntity.optString("id",null),linkEntity.optString("reference_id",null)); return ResponseEntity.ok(Map.of("message","Processed")); } }
  JSONObject entity=payload==null?null:payload.optJSONObject("payment") == null?null:payload.getJSONObject("payment").optJSONObject("entity"); if(entity==null)return ResponseEntity.ok(Map.of("message","Ignored"));
  payments.findByRazorpayOrderId(entity.optString("order_id")).ifPresent(p->{if("payment.failed".equals(event)&&p.getPaymentStatus()!=PaymentStatus.SUCCESS){p.setPaymentStatus(PaymentStatus.FAILED);p.setFailureReason(entity.optString("error_description","Razorpay payment failed"));recovery.detectFailedPayment(payments.save(p));} if("payment.captured".equals(event)&&p.getPaymentStatus()!=PaymentStatus.SUCCESS){p.setPaymentStatus(PaymentStatus.SUCCESS);p.setRazorpayPaymentId(entity.optString("id",null));p.setPaidAt(LocalDateTime.now());p.getOrder().setStatus(OrderStatus.CONFIRMED);orders.save(p.getOrder());recovery.markRecovered(payments.save(p));}});
  return ResponseEntity.ok(Map.of("message","Processed")); }
}
